package su.familyserver.deskmax;

import android.app.*;import android.os.*;import android.content.*;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.media.projection.*;import android.net.Uri;import android.provider.Settings;import android.view.*;import android.widget.*;
import org.json.*;import okhttp3.*;import java.time.Instant;import java.util.concurrent.*;

public final class MainActivity extends Activity {
 private final Handler ui=new Handler(Looper.getMainLooper());private final ExecutorService work=Executors.newSingleThreadExecutor();private final DeskApi api=new DeskApi(DeskApi.DEFAULT_SERVER);
 private static volatile DeskApi.Identity processIdentity;private DeskApi.Identity identity;private TextView code,status,timer;private EditText target;private LinearLayout content;private SessionSocket session;private String pendingHost,viewerId;private boolean active,dialogVisible,destroyed,polling,requesting;private long expires;private RemoteView remote;private Bitmap queuedFrame;private boolean framePosted;private int viewerChildren;private int connectGeneration;private boolean sawHostRunning;
 private final Runnable tick=new Runnable(){public void run(){if(destroyed)return;if(ScreenShareService.isRunning())sawHostRunning=true;if(sawHostRunning&&!ScreenShareService.isRunning()){sawHostRunning=false;active=false;}timer.setText(expires>0?"Обновление кода через "+Math.max(0,expires-Instant.now().getEpochSecond())+" с":"Получаем временный код");if(identity!=null&&!polling){polling=true;work.execute(()->{try{JSONObject c=api.post("api/devices/"+identity.id+"/code",secret());JSONArray a=api.postArray("api/devices/"+identity.id+"/sessions/incoming",secret());JSONObject v=viewerId==null?null:api.post("api/sessions/"+viewerId+"/status",credentials());ui.post(()->{if(destroyed)return;code.setText(c.optString("code"));try{expires=Instant.parse(c.getString("expiresAt")).getEpochSecond();}catch(Exception ignored){}if(a.length()>0&&!active&&!dialogVisible&&pendingHost==null&&!ScreenShareService.isRunning())incoming(a.optJSONObject(0));if(v!=null)viewerStatus(v);polling=false;});}catch(Exception e){ui.post(()->{polling=false;status.setText("Нет связи с сервером • повторяем");});}});}ui.postDelayed(this,3000);}};
 @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(Color.rgb(16,25,22));build();register();}
 private void build(){ScrollView scroll=new ScrollView(this);scroll.setFillViewport(true);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(dp(22),dp(32),dp(22),dp(24));content.setBackgroundColor(Color.rgb(16,25,22));scroll.addView(content);setContentView(scroll);content.setOnApplyWindowInsetsListener((v,insets)->{v.setPadding(dp(22),dp(22)+insets.getSystemWindowInsetTop(),dp(22),dp(24)+insets.getSystemWindowInsetBottom());return insets;});label("DeskMax",32,0xffedf6f0);label("Ваше пространство. На любом экране.",15,0xffa1b5aa);status=label("Подключение к серверу…",13,0xff70e0b1);
  label("ЭТО УСТРОЙСТВО",12,0xffa1b5aa);code=label("— — —",36,0xffedf6f0);code.setTypeface(android.graphics.Typeface.MONOSPACE);timer=label("Временный код",12,0xffa1b5aa);button("Скопировать код",()->{((android.content.ClipboardManager)getSystemService(CLIPBOARD_SERVICE)).setPrimaryClip(ClipData.newPlainText("DeskMax",code.getText()));toast("Код скопирован");});
  label("Подключиться к экрану",23,0xffedf6f0);target=field("Код другого устройства");target.setTag("target-code");target.setInputType(android.text.InputType.TYPE_CLASS_NUMBER);button("Подключиться",this::connect);button("Остановить сеанс",this::stopSession);
  label("Управление Android",20,0xffedf6f0);label("Владелец подтверждает каждый сеанс и разрешает запись экрана. Для касаний включите службу DeskMax вручную в специальных возможностях. Защищённые экраны не передаются.",14,0xffa1b5aa);button("Специальные возможности",()->startActivity(new Intent(Settings.ACTION_ACCESSIBILITY_SETTINGS)));button("Проверить обновления",this::update);label("Версия "+BuildConfig.VERSION_NAME+" • стабильный канал GitHub",12,0xffa1b5aa);
 }
 private TextView label(String text,int size,int color){TextView v=new TextView(this);v.setText(text);v.setTextSize(size);v.setTextColor(color);v.setPadding(0,dp(10),0,dp(8));content.addView(v);return v;}
 private EditText field(String hint){EditText v=new EditText(this);v.setTextColor(0xffedf6f0);v.setHintTextColor(0xff81978b);v.setHint(hint);v.setSingleLine(true);content.addView(v,new LinearLayout.LayoutParams(-1,dp(56)));return v;}
 private void button(String text,Runnable action){Button b=new Button(this);b.setText(text);b.setAllCaps(false);b.setTextColor(0xff101916);GradientDrawable bg=new GradientDrawable();bg.setColor(0xff70e0b1);bg.setCornerRadius(dp(12));b.setBackground(bg);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(48));p.setMargins(0,dp(8),0,dp(6));content.addView(b,p);b.setOnClickListener(v->action.run());}
 private int dp(int n){return Math.round(n*getResources().getDisplayMetrics().density);}private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}
 private JSONObject secret(){return DeskApi.json("deviceSecret",identity.secret);}private JSONObject credentials(){return DeskApi.json("deviceId",identity.id,"deviceSecret",identity.secret);}
 private void register(){if(destroyed)return;if(processIdentity!=null){identity=processIdentity;ui.post(tick);return;}work.execute(()->{try{JSONObject o=api.post("api/devices",DeskApi.json("deviceName",Build.MANUFACTURER+" "+Build.MODEL,"platform","Android"));identity=new DeskApi.Identity(o.getString("deviceId"),o.getString("deviceSecret"));processIdentity=identity;ui.post(()->{if(destroyed)return;status.setText("Онлайн • доступ только с разрешения");ui.post(tick);});}catch(Exception e){ui.post(()->{if(destroyed)return;status.setText("Сервер недоступен. Повтор через 10 секунд.");ui.postDelayed(this::register,10000);});}});}
 private void connect(){if(identity==null||requesting||active||viewerId!=null||pendingHost!=null||ScreenShareService.isRunning()){toast("Дождитесь подключения или остановите сеанс");return;}String c=target.getText().toString().trim();if(c.isEmpty())return;requesting=true;int generation=++connectGeneration;status.setText("Запрашиваем разрешение владельца…");work.execute(()->{try{JSONObject o=api.post("api/sessions",DeskApi.json("targetCode",c,"requesterDeviceId",identity.id,"requesterDeviceSecret",identity.secret));ui.post(()->{if(destroyed||generation!=connectGeneration){stopRequest(o.optString("sessionId"));return;}requesting=false;viewerId=o.optString("sessionId");viewerStatus(o);});}catch(Exception e){ui.post(()->{requesting=false;if(!destroyed)status.setText("Не удалось подключиться: проверьте код");});}});}
 private void viewerStatus(JSONObject o){String s=o.optString("status");if(s.equals("approved")&&!active){active=true;startViewer(viewerId);}else if(s.equals("pending-owner-confirmation"))status.setText("Ожидаем подтверждения владельца…");else if(!s.equals("approved")){viewerId=null;status.setText("Запрос завершён: "+s);}}
 private void incoming(JSONObject o){if(destroyed||pendingHost!=null||ScreenShareService.isRunning()||o==null||!o.optString("status").equals("pending-owner-confirmation"))return;dialogVisible=true;String id=o.optString("sessionId");new AlertDialog.Builder(this).setTitle("Разрешить доступ к экрану?").setMessage(o.optString("requesterDeviceName")+" сможет видеть экран"+(RemoteAccessibilityService.isEnabled(this)?" и управлять устройством.":". Управление касаниями отключено.")).setPositiveButton("Разрешить",(d,w)->{pendingHost=id;MediaProjectionManager m=(MediaProjectionManager)getSystemService(MEDIA_PROJECTION_SERVICE);Intent intent=Build.VERSION.SDK_INT>=34?m.createScreenCaptureIntent(MediaProjectionConfig.createConfigForDefaultDisplay()):m.createScreenCaptureIntent();startActivityForResult(intent,42);}).setNegativeButton("Отклонить",(d,w)->reject(id)).setOnCancelListener(d->reject(id)).setOnDismissListener(d->dialogVisible=false).show();}
 private void reject(String id){work.execute(()->{try{api.post("api/sessions/"+id+"/reject",secret());}catch(Exception ignored){}});}
 @Override protected void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);if(request!=42)return;String id=pendingHost;pendingHost=null;if(id==null||destroyed)return;if(result!=RESULT_OK||data==null){reject(id);return;}active=true;int generation=++connectGeneration;work.execute(()->{try{api.post("api/sessions/"+id+"/approve",secret());ui.post(()->{if(destroyed||generation!=connectGeneration){stopRequest(id);return;}try{ScreenShareService.begin(this,DeskApi.DEFAULT_SERVER,identity,id,result,data);status.setText("Экран передаётся • остановите сеанс кнопкой");}catch(Exception e){active=false;status.setText("Не удалось начать передачу");}});}catch(Exception e){ui.post(()->{active=false;status.setText("Запрос доступа истёк");});}});}
 private void startViewer(String id){status.setText("Ожидаем экран…");viewerChildren=content.getChildCount();remote=new RemoteView();content.addView(remote,0,new LinearLayout.LayoutParams(-1,dp(300)));EditText text=field("\u0422\u0435\u043a\u0441\u0442 \u0434\u043b\u044f \u0443\u0441\u0442\u0440\u043e\u0439\u0441\u0442\u0432\u0430");text.setFilters(new android.text.InputFilter[]{new android.text.InputFilter.LengthFilter(1024)});button("\u041e\u0442\u043f\u0440\u0430\u0432\u0438\u0442\u044c \u0442\u0435\u043a\u0441\u0442",()->{String value=text.getText().toString();if(ProtocolLimits.validText(value)){input(DeskApi.json("kind","text","text",value));text.setText("");}});button("Enter",()->press(13));button("Backspace",()->press(8));button("Esc",()->press(27));button("Прокрутить вверх",()->input(DeskApi.json("kind","wheel","delta",120)));button("Прокрутить вниз",()->input(DeskApi.json("kind","wheel","delta",-120)));
 session=new SessionSocket(DeskApi.DEFAULT_SERVER,identity,id,false,new SessionSocket.Listener(){public void onReady(){ui.post(()->status.setText("Подключено • касание и перетаскивание"));}public void onFrame(byte[] b){BitmapFactory.Options opts=new BitmapFactory.Options();opts.inJustDecodeBounds=true;BitmapFactory.decodeByteArray(b,0,b.length,opts);if(opts.outWidth<1||opts.outHeight<1||(long)opts.outWidth*opts.outHeight>16777216){ui.post(MainActivity.this::stopSession);return;}Bitmap image=BitmapFactory.decodeByteArray(b,0,b.length);synchronized(MainActivity.this){if(destroyed||!active){if(image!=null)image.recycle();return;}if(queuedFrame!=null)queuedFrame.recycle();queuedFrame=image;if(framePosted)return;framePosted=true;}ui.post(()->{Bitmap next;synchronized(MainActivity.this){next=queuedFrame;queuedFrame=null;framePosted=false;}if(remote!=null&&active)remote.frame(next);else if(next!=null)next.recycle();});}public void onInput(JSONObject o){}public void onClosed(String why){ui.post(()->{if(!destroyed){clearViewer();active=false;viewerId=null;status.setText(why);}});}});session.start();}
 private void input(JSONObject o){if(session!=null)session.sendInput(o);}private void key(int k,boolean down){input(DeskApi.json("kind",down?"keyDown":"keyUp","key",k));}private void press(int k){key(k,true);key(k,false);}
 private void stopRequest(String id){DeskApi.HTTP.newCall(new Request.Builder().url(DeskApi.DEFAULT_SERVER+"api/sessions/"+id+"/stop").post(RequestBody.create(credentials().toString(),MediaType.get("application/json"))).build()).enqueue(new Callback(){public void onFailure(Call c,java.io.IOException e){}public void onResponse(Call c,Response r){r.close();}});}
 private void stopSession(){++connectGeneration;requesting=false;if(pendingHost!=null){reject(pendingHost);pendingHost=null;}if(session!=null){session.stop();session=null;}if(viewerId!=null&&identity!=null){String id=viewerId;work.execute(()->{try{api.post("api/sessions/"+id+"/stop",credentials());}catch(Exception ignored){}});}ScreenShareService.requestStop(this);active=false;viewerId=null;status.setText("Сеанс остановлен");clearViewer();}
 private void clearViewer(){if(remote!=null){content.removeView(remote);remote.frame(null);remote=null;while(content.getChildCount()>viewerChildren)content.removeViewAt(content.getChildCount()-1);}synchronized(this){if(queuedFrame!=null){queuedFrame.recycle();queuedFrame=null;}}}
 private void update(){work.execute(()->{try(Response r=DeskApi.HTTP.newCall(new Request.Builder().url("https://api.github.com/repos/ignatovmax1/DeskMax/releases/latest").header("Accept","application/vnd.github+json").build()).execute()){if(!r.isSuccessful()||r.body()==null)throw new Exception();JSONObject o=new JSONObject(r.body().string());if(o.optBoolean("draft")||o.optBoolean("prerelease")||!ProtocolLimits.newerRelease(o.optString("tag_name"),BuildConfig.VERSION_NAME)){ui.post(()->toast("DeskMax "+BuildConfig.VERSION_NAME));return;}JSONArray assets=o.getJSONArray("assets");String url=null;for(int i=0;i<assets.length();i++){JSONObject a=assets.getJSONObject(i);if(a.optString("name").equals("DeskMax-Android.apk"))url=a.optString("browser_download_url");}String asset=url;if(asset==null||!asset.startsWith("https://github.com/ignatovmax1/DeskMax/releases/download/"))throw new Exception();ui.post(()->new AlertDialog.Builder(this).setTitle("GitHub • "+o.optString("tag_name")).setMessage("Открыть APK стабильного релиза? Android запросит разрешение на установку. Обновите оба устройства.").setPositiveButton("Открыть",(d,w)->startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(asset)))).setNegativeButton("Отмена",null).show());}catch(Exception e){ui.post(()->toast("Обновление пока недоступно"));}});}
 @Override protected void onPause(){super.onPause();if(session!=null)input(DeskApi.json("kind","releaseAll"));}
 @Override protected void onDestroy(){destroyed=true;ui.removeCallbacksAndMessages(null);if(session!=null)session.stop();clearViewer();work.shutdown();super.onDestroy();}
 private final class RemoteView extends View {Bitmap bitmap;Paint paint=new Paint(3);boolean down;double lastX,lastY;RemoteView(){super(MainActivity.this);setTag("remote-screen");setBackgroundColor(0xff080e0b);}void frame(Bitmap next){Bitmap old=bitmap;bitmap=next;invalidate();if(old!=null&&old!=next)old.recycle();}@Override protected void onDraw(Canvas c){if(bitmap==null)return;float scale=Math.min((float)getWidth()/bitmap.getWidth(),(float)getHeight()/bitmap.getHeight()),w=bitmap.getWidth()*scale,h=bitmap.getHeight()*scale;c.drawBitmap(bitmap,null,new RectF((getWidth()-w)/2,(getHeight()-h)/2,(getWidth()+w)/2,(getHeight()+h)/2),paint);}@Override public boolean onTouchEvent(android.view.MotionEvent e){if(bitmap==null)return true;double[] p=RemoteGeometry.point(e.getX(),e.getY(),getWidth(),getHeight(),bitmap.getWidth(),bitmap.getHeight());int a=e.getActionMasked();if(p!=null){lastX=p[0];lastY=p[1];input(DeskApi.json("kind","move","x",p[0],"y",p[1]));if(a==MotionEvent.ACTION_DOWN){down=true;getParent().requestDisallowInterceptTouchEvent(true);input(DeskApi.json("kind","down","button","left","x",p[0],"y",p[1]));}}if(a==MotionEvent.ACTION_UP||a==MotionEvent.ACTION_CANCEL){if(down)input(a==MotionEvent.ACTION_UP?DeskApi.json("kind","up","button","left","x",lastX,"y",lastY):DeskApi.json("kind","releaseAll"));getParent().requestDisallowInterceptTouchEvent(false);down=false;performClick();}return true;}@Override public boolean performClick(){super.performClick();return true;}}
}
