namespace DeskMax.Contracts;
public record RegisterDeviceRequest(string DeviceName, string Platform);
public record RegisterDeviceResponse(string DeviceId, string DeviceSecret, DateTimeOffset RegisteredAt);
public record RotatingCodeResponse(string DeviceId, string Code, DateTimeOffset ExpiresAt);
public record CreateSessionRequest(string TargetCode, string RequesterDeviceId, string RequesterDeviceSecret);
public record SessionResponse(Guid SessionId, string Status, string TargetDeviceId, DateTimeOffset ExpiresAt);
public record ApproveSessionRequest(string DeviceSecret);
public record SessionCredentialsRequest(string DeviceId, string DeviceSecret);
public record IncomingSessionResponse(Guid SessionId, string RequesterDeviceId, string RequesterDeviceName, string Status, DateTimeOffset ExpiresAt);
public record GrantAccessRequest(string OwnerDeviceSecret, string TrustedDeviceId, DateTimeOffset? ExpiresAt);
