<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\DeskMax.Contracts\DeskMax.Contracts.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <Version>0.4.3</Version>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AssemblyName>DeskMax</AssemblyName>
    <RootNamespace>DeskMax.Windows</RootNamespace>
  </PropertyGroup>

</Project>
